[project]
name = "assignment1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "psycopg2>=2.9.10",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.41",
]
